name: PlatformIO Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  UNIFIED_FW:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Build Prod PCB FW
        run: |
          pio run -e unified
      - uses: actions/upload-artifact@v3
        with:
          name: UNIFIED_FW
          path: |
            .pio/build/unified/firmware.elf
            .pio/build/unified/firmware.bin
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: pyTooling/Actions/releaser@r0
        with:
          tag: ${{ github.head_ref }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}-${{ steps.date.outputs.date }}
          files: |
            .pio/build/unified/firmware.elf
            .pio/build/unified/firmware.bin
